Repository compilers-uff/lexer-e-parser-grupo-2, pull requests merged in 2025-04, with the labels that each got.

#3 feat: add operator tokens for lexical analysis
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
  src/test/data/pa1/sample/operators_identifiers_test.py
Labels: enhancement

#5 Tokens de <idstring> e <string>
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
  src/test/data/pa1/sample/expr_string.py
Labels: enhancement

#6 Token Integer Literal
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
  src/test/data/pa1/own_tests/expr_string.py
  src/test/data/pa1/own_tests/int_max_test.py
  src/test/data/pa1/own_tests/operators_identifiers_test.py
Labels: enhancement

#8 Implementação da analise léxica de identações
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
  src/test/data/pa1/own_tests/indentation.py
Labels: enhancement

#9 fix: handle dedent in eof
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
  src/test/data/pa1/own_tests/class_def.py
Labels: enhancement

#12 Correção do match do integer literal
  src/main/cup/chocopy/pa1/ChocoPy.cup
Labels: bug

#13 Definição de variaveis
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/test/data/pa1/own_tests/var_decl.py
Labels: enhancement

#14 Declarações de escopo de variável
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/test/data/pa1/own_tests/global_decl.py
  src/test/data/pa1/own_tests/nonlocal_decl.py
Labels: enhancement

#15 Feat/classdef parser
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/test/data/pa1/own_tests/class_def.py
Labels: enhancement

#18 Feat/expressions
  src/main/cup/chocopy/pa1/ChocoPy.cup
Labels: enhancement

#17 feat: create program rules for parser
  src/main/cup/chocopy/pa1/ChocoPy.cup
Labels: enhancement

#16 Feat/funcdef parser
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/test/data/pa1/own_tests/func_def.py
Labels: enhancement

#19 Feat/expressions
  src/main/cup/chocopy/pa1/ChocoPy.cup
Labels: bug

#20 fix:fix errors in nonterminal declarations
  src/main/cup/chocopy/pa1/ChocoPy.cup
Labels: bug

#21 fix: add identifier instance and var name errors
  src/main/cup/chocopy/pa1/ChocoPy.cup
Labels: bug

#22 Feat/implement stmt
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/test/data/pa1/own_tests/stmts.py
Labels: enhancement

#23 Fix/parsing problems
  sla.json
  src/main/cup/chocopy/pa1/ChocoPy.cup
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
  src/test/data/pa1/own_tests/pass.py
  src/test/data/pa1/own_tests/strings.py
  teste.py
Labels: bug

#24 Doc/lexer comments
  README.md
  src/main/jflex/chocopy/pa1/ChocoPy.jflex
  src/test/data/pa1/student_contributed/good.py
Labels: documentation
